# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 13:56
from __future__ import unicode_literals

from django.db import migrations
import member.models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', member.models.CustomUserManager()),
            ],
        ),
    ]
