# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 14:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="전화번호는 '010-1234-5678','01012345678','02-1234-5678', '0212345678' 형식으로 입력하여야 합니다.", regex='^0([0-9]{1,2})-?([0-9]{3,4})-?([0-9]{4})$')]),
        ),
    ]
